export const PRESETS = [
  {
    id: 'seq-101',
    name: 'Sequence detector 101',
    blurb: 'Outputs 1 the moment the substring 101 completes — including overlapping matches.',
    states: ['q0', 'q1', 'q2'],
    initial: 'q0',
    transitions: [
      { from: 'q0', input: '0', output: '0', to: 'q0' },
      { from: 'q0', input: '1', output: '0', to: 'q1' },
      { from: 'q1', input: '0', output: '0', to: 'q2' },
      { from: 'q1', input: '1', output: '0', to: 'q1' },
      { from: 'q2', input: '1', output: '1', to: 'q1' },
      { from: 'q2', input: '0', output: '0', to: 'q0' },
    ],
    sample: '10101',
  },
  {
    id: 'mod4',
    name: 'Modulo-4 counter',
    blurb: 'Counts 1s mod 4. A 1 increments and emits the new value; a 0 holds.',
    states: ['q0', 'q1', 'q2', 'q3'],
    initial: 'q0',
    transitions: [
      { from: 'q0', input: '0', output: '0', to: 'q0' },
      { from: 'q0', input: '1', output: '1', to: 'q1' },
      { from: 'q1', input: '0', output: '0', to: 'q1' },
      { from: 'q1', input: '1', output: '1', to: 'q2' },
      { from: 'q2', input: '0', output: '0', to: 'q2' },
      { from: 'q2', input: '1', output: '1', to: 'q3' },
      { from: 'q3', input: '0', output: '0', to: 'q3' },
      { from: 'q3', input: '1', output: '1', to: 'q0' },
    ],
    sample: '11110',
  },
  {
    id: 'ends11',
    name: 'Ends in 11',
    blurb: 'Emits 1 on every 1 that completes a pair of consecutive 1s.',
    states: ['q0', 'q1'],
    initial: 'q0',
    transitions: [
      { from: 'q0', input: '0', output: '0', to: 'q0' },
      { from: 'q0', input: '1', output: '0', to: 'q1' },
      { from: 'q1', input: '0', output: '0', to: 'q0' },
      { from: 'q1', input: '1', output: '1', to: 'q1' },
    ],
    sample: '110111',
  },
  {
    id: 'ud-counter',
    name: 'Up / down counter',
    blurb: 'Three-symbol alphabet: u increments, d decrements, n holds.',
    states: ['q0', 'q1', 'q2', 'q3'],
    initial: 'q0',
    transitions: [
      { from: 'q0', input: 'n', output: '0', to: 'q0' },
      { from: 'q0', input: 'u', output: '1', to: 'q1' },
      { from: 'q0', input: 'd', output: '3', to: 'q3' },
      { from: 'q1', input: 'n', output: '0', to: 'q1' },
      { from: 'q1', input: 'u', output: '2', to: 'q2' },
      { from: 'q1', input: 'd', output: '0', to: 'q0' },
      { from: 'q2', input: 'n', output: '0', to: 'q2' },
      { from: 'q2', input: 'u', output: '3', to: 'q3' },
      { from: 'q2', input: 'd', output: '1', to: 'q1' },
      { from: 'q3', input: 'n', output: '0', to: 'q3' },
      { from: 'q3', input: 'u', output: '0', to: 'q0' },
      { from: 'q3', input: 'd', output: '2', to: 'q2' },
    ],
    sample: 'uudnnd',
  },
  {
    id: 'traffic',
    name: 'Traffic light',
    blurb: 'g requests green, r requests red. Output 1 marks a lamp that just switched on.',
    states: ['R', 'G', 'Y'],
    initial: 'R',
    transitions: [
      { from: 'R', input: 'g', output: '1', to: 'G' },
      { from: 'R', input: 'r', output: '0', to: 'R' },
      { from: 'G', input: 'r', output: '0', to: 'Y' },
      { from: 'G', input: 'g', output: '0', to: 'G' },
      { from: 'Y', input: 'r', output: '1', to: 'R' },
      { from: 'Y', input: 'g', output: '0', to: 'G' },
    ],
    sample: 'grgrg',
  },
  {
    id: 'toggle',
    name: 'Toggle flip-flop',
    blurb: 'The smallest non-trivial Mealy machine: two states, one symbol.',
    states: ['off', 'on'],
    initial: 'off',
    transitions: [
      { from: 'off', input: '0', output: '0', to: 'off' },
      { from: 'off', input: '1', output: '1', to: 'on' },
      { from: 'on', input: '0', output: '0', to: 'on' },
      { from: 'on', input: '1', output: '0', to: 'off' },
    ],
    sample: '1011010',
  },
]

export const BLANK_MACHINE = {
  states: ['q0', 'q1'],
  initial: 'q0',
  transitions: [
    { from: 'q0', input: '0', output: '0', to: 'q0' },
    { from: 'q0', input: '1', output: '0', to: 'q1' },
    { from: 'q1', input: '0', output: '0', to: 'q0' },
    { from: 'q1', input: '1', output: '1', to: 'q1' },
  ],
  sample: '0101',
}
